server:
  port: 8085
  servletPath: /

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bom_test?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true