server:
  port: 8084
  servletPath: /
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
      enabled: true
    instance:
      healthCheckUrlPath: ${server.servletPath}/health
      statusPageUrlPath: ${server.servletPath}/info
      homePageUrl: ${server.servletPath}/
      healthcheck:
        enabled: true
spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  application:
    name: app-order
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/bom_mail?useSSL=false&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
